[phases.setup]
aptPkgs = ["...", "ffmpeg", "curl"]

[phases.build]
cmds = [
    "npm install",
    "mkdir -p ./bin",
    "curl -L https://github.com/yt-dlp/yt-dlp/releases/latest/download/yt-dlp_linux -o ./bin/yt-dlp",
    "chmod a+rx ./bin/yt-dlp",
    "npm run build"
]
